version: '3.8'

services:
  web:
    build:
      context: ./.warden/fastapi
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --reload --host 0.0.0.0 --port 80'
    volumes:
      - .:/app
    expose:
      - 80
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
    depends_on:
      - db
    labels: # new
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`app.fastapi.test`)"
      - "traefik.http.routers.fastapi.tls=true"
    networks:
      - default
      - scrubsandbeyondphp8_default
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik
volumes:
  postgres_data:
networks:
  scrubsandbeyondphp8_default:
    name: scrubsandbeyondphp8_default