version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: ./.warden/fastapi/Dockerfile
    volumes:
      - .:/app
    expose:
      - 80
    environment:
      - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
    depends_on:
      - db
    labels: # new
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`$TRAEFIK_SUBDOMAIN.$TRAEFIK_DOMAIN`)"
      - "traefik.http.routers.fastapi.tls=true"
    networks:
      - default
      - project_network
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
volumes:
  postgres_data:
networks:
  project_network:
    name: $PROJECT_NETWORK